# Generated by Django 3.1.5 on 2021-01-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='student',
            field=models.ManyToManyField(blank=True, to='users.Student'),
        ),
    ]
