# Generated by Django 3.1.5 on 2021-01-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20210119_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('notice', models.CharField(max_length=500)),
                ('visited', models.BooleanField(default=False)),
                ('modified_date', models.DateField(auto_now=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GroupNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('notice', models.CharField(max_length=500)),
                ('visited', models.BooleanField(default=False)),
                ('modified_date', models.DateField(auto_now=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.interest')),
                ('nclass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='ConcessionApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_station', models.CharField(max_length=20)),
                ('to_station', models.CharField(max_length=20)),
                ('duration', models.CharField(choices=[('MON', 'MONTHLY'), ('QTY', 'QUATERLY')], default='MON', max_length=3)),
                ('train_class', models.CharField(choices=[('FC', 'FIRST CLASS'), ('SC', 'SECOND CLASS')], default='SC', max_length=2)),
                ('prev_ticket_no', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('APR', 'APPROVE'), ('CAN', 'CANCEL')], default='NEW', max_length=3)),
                ('modified_date', models.DateField(auto_now=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
