# Generated by Django 3.1.5 on 2021-01-18 19:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.CharField(max_length=7, verbose_name='Examination Year')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('prac_score', models.CharField(max_length=7, verbose_name='Practical Score')),
                ('term_score', models.CharField(max_length=7, verbose_name='Termwork Score')),
                ('ia_score', models.CharField(max_length=7, verbose_name='Internal Assessment Score')),
                ('ese_score', models.CharField(max_length=7, verbose_name='End Semester Exam Score')),
                ('total_score', models.CharField(max_length=7, verbose_name='Total Score')),
            ],
            options={
                'verbose_name_plural': 'Marks',
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_point', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY')], max_length=3)),
                ('timing', models.CharField(choices=[('08:00-09:00', '08:00-09:00'), ('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:15-12:15', '11:15-12:15'), ('12:15-13:15', '12:15-13:15'), ('13:45-14:45', '13:45-14:45'), ('14:45-15:45', '14:45-15:45'), ('15:45-16:45', '15:45-16:45'), ('16:45-17:45', '16:45-17:45'), ('17:45-18:45', '17:45-18:45')], max_length=11)),
                ('classroom', models.CharField(max_length=15)),
                ('batch', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
        ),
    ]
