# Generated by Django 3.2.7 on 2021-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20210119_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY'), (6, 'SUNDAY')]),
        ),
    ]
